// components/actor_card.vue
<template>
  <card :color="actor.thumbnail && actor.thumbnail.color">
    <template #image>
      <a :to="`/actor/${actor._id}`">
        <responsive-image
          :ratio="4 / 3"
          :src="`/api/media/image/${actor.thumbnail && actor.thumbnail._id}/thumbnail?password=xxx`"
          class="thumbnail hover"
          style="background: #303030"
          :alt="`${actor.name} thumbnail`"
        >
          <slot name="overlay" />
        </responsive-image>
      </a>
    </template>
    <template #body>
      <div style="margin-bottom: 4px; display: flex; align-items: center">
        <div class="flex" style="margin-right: 5px" v-if="actor.nationality">
          <flag
            :name="`${actor.nationality.name} (${actor.nationality.nationality})`"
            :width="22"
            :value="actor.nationality.alpha2"
          />
        </div>
        <div class="actor-name" :title="actor.name">
          <b>{{ actor.name }}</b>
        </div>
        <div style="flex-grow: 1"></div>
        <div v-if="actor.age" class="age">
          {{ actor.age }}
        </div>
      </div>

      <div class="rating">
        <Rating :value="actor.rating" color="black" />
      </div>

      <div v-if="actor.labels.length">
        <label-group :limit="5" :labels="actor.labels"></label-group>
      </div>
    </template>
  </card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import Card from "./card.vue";
import LabelGroup from "./label_group.vue";
import Rating from "./rating.vue";
import ResponsiveImage from "./image.vue";
import Flag from "./flag.vue";

export default defineComponent({
  components: { Card, Flag, LabelGroup, Rating, ResponsiveImage },
  props: {
    actor: {
      type: Object,
    },
  },
});
</script>

<style>
.overlay-bottom {
  display: flex;
  align-items: center;
  padding: 2px;
}

.round-button {
  border-radius: 50%;
  padding: 4px;
  width: 40px;
  height: 40px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: white;
}

.age {
  font-weight: bold;
}

.actor-name {
  font-size: 16.5px;
  white-space: nowrap;
  width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
}

.rating {
  font-size: 17px;
  font-weight: bold;
  margin-bottom: 6px;
}
</style>

// components/ActorCard.tsx
import Card from "@mui/material/Card";
import Color from "color";

import HeartIcon from "@mui/icons-material/Favorite";
import HeartBorderIcon from "@mui/icons-material/FavoriteBorder";
import BookmarkIcon from "@mui/icons-material/Bookmark";
import BookmarkBorderIcon from "@mui/icons-material/BookmarkBorder";

import Rating from "./Rating";
import { IActor } from "../types/actor";

function thumbnailUrl(thumbnail: string) {
  return `/api/media/image/${thumbnail}/thumbnail?password=xxx`;
}

export default function ActorCard({ actor }: { actor: IActor }) {
  return (
    <Card style={{ position: "relative" }} sx={{ borderRadius: 2 }} variant="outlined">
      <div>
        <img
          style={{ objectFit: "contain", aspectRatio: "3 / 4" }}
          width="100%"
          src={thumbnailUrl(actor.thumbnail?._id || "null")}
        />
      </div>
      <div style={{ position: "absolute", left: 2, top: 2 }}>
        {actor.favorite ? (
          <HeartIcon style={{ fontSize: 28, color: "#ff3355" }} />
        ) : (
          <HeartBorderIcon style={{ fontSize: 28 }} />
        )}
        {actor.bookmark ? (
          <BookmarkIcon style={{ fontSize: 28 }} />
        ) : (
          <BookmarkBorderIcon style={{ fontSize: 28 }} />
        )}
      </div>
      <div style={{ margin: "0px 8px 8px 8px" }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            fontWeight: 600,
            fontSize: 16,
            gap: 5,
          }}
        >
          {actor.nationality && (
            <img
              width="20"
              height="20"
              src={`/assets/flags/${actor.nationality.alpha2.toLowerCase()}.svg`}
            />
          )}
          <div
            style={{
              whiteSpace: "nowrap",
              textOverflow: "ellipsis",
              overflow: "hidden",
            }}
          >
            {actor.name}
          </div>
          <div style={{ flexGrow: 1 }}></div>
          <div>{actor.age}</div>
        </div>

        <div style={{ marginTop: 5 }}>
          <Rating value={actor.rating || 0} readonly />
        </div>

        <div style={{ marginTop: 5 }}>
          {actor.labels.map((label) => (
            <div
              style={{
                opacity: 0.75,
                fontSize: 12,
                padding: "2px 8px 2px 8px",
                borderRadius: 4,
                display: "inline-block",
                marginRight: 4,
                marginTop: 4,
                background: label.color || "transparent",
                color: new Color(label.color).isLight() ? "black" : "white",
              }}
              key={label._id}
            >
              {label.name}
            </div>
          ))}
        </div>
      </div>
    </Card>
  );
}
