// components/list_container.vue
<template>
  <div
    class="list-container"
    :style="{
      'grid-template-columns': `repeat(auto-fill, minmax(${min}, ${max}))`,
      'grid-gap': `${gap} ${gap}`,
    }"
  >
    <slot />
  </div>
</template>

<script>
export default {
  props: {
    min: {
      type: String,
      default: "275px",
    },
    max: {
      type: String,
      default: "1fr",
    },
    gap: {
      type: String,
      default: "0.5em",
    },
  },
};
</script>

<style scoped>
.list-container {
  display: grid;
}
</style>

// components/ListContainer.tsx
import { ReactNode } from "react";

type Props = {
  children: ReactNode;
  size?: number;
  gap?: number;
};

export default function ListContainer({ children, size, gap }: Props): JSX.Element {
  return (
    <div
      className="list-container"
      style={{
        display: "grid",
        gridTemplateColumns: `repeat(auto-fill, minmax(${size || 200}px, 1fr))`,
        gridGap: gap || 5,
      }}
    >
      {children}
    </div>
  );
}
