// components/scene_card.vue
<template>
  <div
    class="scene card rounded"
    :style="{
      background: `${(scene.thumbnail && scene.thumbnail.color) || 'white'} !important`,
    }"
  >
    <nuxt-link :to="`/scene/${scene._id}`">
      <img
        :src="`/api/media/image/${scene.thumbnail && scene.thumbnail._id}/thumbnail?password=xxx`"
        :alt="scene.name"
        class="thumb hover"
        style="background: #202020"
      />
    </nuxt-link>

    <div
      class="card-body"
      :style="{
        color: scene.thumbnail && scene.thumbnail.color ? 'white' : 'black',
      }"
    >
      <div style="display: flex">
        <div v-if="scene.studio" class="studio-name">
          <b>{{ scene.studio.name }}</b>
        </div>
        <div style="flex-grow: 1"></div>
        <div v-if="scene.releaseDate" class="release-date">
          {{ new Date(scene.releaseDate).toLocaleDateString() }}
        </div>
      </div>

      <div class="scene-name" :title="scene.name">
        <b>{{ scene.name }}</b>
      </div>

      <div class="actor-names">
        <span>With </span>
        <span v-for="(actor, i) in scene.actors" :key="actor._id">
          <b>{{ actor.name }}</b
          ><span v-if="i < scene.actors.length - 1">{{
            i === scene.actors.length - 2 ? " & " : ", "
          }}</span>
        </span>
      </div>

      <div class="rating">{{ (scene.rating / 2).toFixed(1) }}★</div>

      <div v-if="scene.labels.length">
        {{ scene.labels.map((l) => l.name).slice(0, 5) }}
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: ["scene"],
};
</script>

<style scoped>
.scene {
  display: flex;
  flex-direction: column;
  overflow: hidden;
  box-shadow: rgba(0, 0, 0, 0.15) 1.95px 1.95px 2.6px !important;
}

.thumb {
  width: 100%;
  height: auto;
}

.card-body {
  text-align: left;
  flex-grow: 1;
  padding: 8px;
}

.studio-name {
  text-transform: uppercase;
  font-size: 12px;
  opacity: 0.75;
  margin-bottom: 4px;
}

.scene-name {
  font-size: 16.5px;
  margin-bottom: 6px;

  white-space: nowrap;
  width: 100%;
  overflow: hidden;
  text-overflow: ellipsis;
}

.actor-names {
  font-size: 13.5px;
  margin-bottom: 6px;
}

.rating {
  font-size: 17px;
  font-weight: bold;
  margin-bottom: 6px;
}

.release-date {
  font-size: 13.5px;
}
</style>

// components/SceneCard.tsx
import { IScene } from "../types/scene";
import Card from "./Card";
import Link from "next/link";

import HeartIcon from "mdi-react/HeartIcon";
import HeartBorderIcon from "mdi-react/HeartOutlineIcon";
import BookmarkIcon from "mdi-react/BookmarkIcon";
import BookmarkBorderIcon from "mdi-react/BookmarkOutlineIcon";

import Rating from "./Rating";
import LabelGroup from "./LabelGroup";
import { thumbnailUrl } from "../util/thumbnail";
import { formatDuration } from "../util/string";

export default function SceneCard({ scene }: { scene: IScene }) {
  return (
    <Card style={{ position: "relative" }}>
      <div style={{ position: "relative" }}>
        <Link href={`/scene/${scene._id}`} passHref>
          <a style={{ display: "block" }} className="hover">
            <img
              style={{ objectFit: "cover", aspectRatio: "4 / 3" }}
              width="100%"
              src={thumbnailUrl(scene.thumbnail?._id || "null")}
            />
          </a>
        </Link>
        <div
          style={{
            display: "flex",
            gap: 2,
            fontSize: 14,
            fontWeight: "bold",
            color: "white",
            position: "absolute",
            right: 5,
            bottom: 5,
          }}
        >
          <div style={{ borderRadius: 4, padding: "2px 5px", background: "#000000dd" }}>
            {formatDuration(scene.meta.duration)}
          </div>
        </div>
      </div>
      <div
        style={{
          color: "white",
          display: "flex",
          alignItems: "center",
          background: "#000000bb",
          borderRadius: 5,
          padding: 3,
          position: "absolute",
          left: 0,
          top: 0,
        }}
      >
        {scene.favorite ? (
          <HeartIcon style={{ fontSize: 28, color: "#ff3355" }} />
        ) : (
          <HeartBorderIcon style={{ fontSize: 28 }} />
        )}
        {scene.bookmark ? (
          <BookmarkIcon style={{ fontSize: 28 }} />
        ) : (
          <BookmarkBorderIcon style={{ fontSize: 28 }} />
        )}
      </div>
      <div style={{ margin: "4px 8px 8px 8px" }}>
        <div style={{ display: "flex" }}>
          {scene.studio && (
            <div
              style={{ textTransform: "uppercase", marginBottom: 5, fontSize: 13, opacity: 0.8 }}
            >
              {scene.studio.name}
            </div>
          )}
          <div style={{ flexGrow: 1 }}></div>
          {scene.releaseDate && (
            <div style={{ fontSize: 13, opacity: 0.75 }}>
              {new Date(scene.releaseDate).toLocaleDateString()}
            </div>
          )}
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            fontWeight: 600,
            fontSize: 16,
            gap: 5,
          }}
        >
          <div
            style={{
              whiteSpace: "nowrap",
              textOverflow: "ellipsis",
              overflow: "hidden",
            }}
          >
            {scene.name}
          </div>
        </div>

        <div style={{ marginTop: 5 }}>
          <Rating value={scene.rating || 0} readonly />
        </div>

        <div style={{ marginTop: 5 }}>
          <LabelGroup labels={scene.labels} />
        </div>
      </div>
    </Card>
  );
}
