// components/MovieCard.tsx
import HeartIcon from "mdi-react/HeartIcon";
import HeartBorderIcon from "mdi-react/HeartOutlineIcon";
import BookmarkIcon from "mdi-react/BookmarkIcon";
import BookmarkBorderIcon from "mdi-react/BookmarkOutlineIcon";

import Card from "./Card";
import Rating from "./Rating";
import Link from "next/link";
import LabelGroup from "./LabelGroup";
import { IMovie } from "../types/movie";
import moment from "moment";
import { useState } from "react";

function thumbnailUrl(thumbnail: string) {
  return `/api/media/image/${thumbnail}/thumbnail?password=xxx`;
}

function movieDuration(secs: number): string {
  return moment()
    .startOf("day")
    .seconds(secs)
    .format(secs < 3600 ? "mm:ss" : "H:mm:ss");
}

export default function MovieCard({ movie }: { movie: IMovie }) {
  const [hover, setHover] = useState(false);

  return (
    <Card style={{ position: "relative" }}>
      <div style={{ position: "relative" }}>
        <Link href={`/movie/${movie._id}`} passHref>
          <a style={{ display: "block" }} className="hover">
            <img
              onMouseLeave={() => setHover(false)}
              onMouseEnter={() => setHover(true)}
              style={{ objectFit: "contain", aspectRatio: "3 / 4" }} // TODO: for some reason aspect-ratio is not working correctly here
              width="100%"
              src={
                hover
                  ? thumbnailUrl(movie.backCover?._id || "null")
                  : thumbnailUrl(movie.frontCover?._id || "null")
              }
            />
          </a>
        </Link>
        <div
          style={{
            fontSize: 14,
            fontWeight: "bold",
            color: "white",
            background: "#000000dd",
            borderRadius: 5,
            padding: "2px 5px",
            position: "absolute",
            right: 5,
            bottom: 5,
          }}
        >
          {movieDuration(movie.duration)}
        </div>
      </div>
      <div
        style={{
          color: "white",
          display: "flex",
          alignItems: "center",
          background: "#000000bb",
          borderRadius: 5,
          padding: 3,
          position: "absolute",
          left: 0,
          top: 0,
        }}
      >
        {movie.favorite ? (
          <HeartIcon style={{ fontSize: 28, color: "#ff3355" }} />
        ) : (
          <HeartBorderIcon style={{ fontSize: 28 }} />
        )}
        {movie.bookmark ? (
          <BookmarkIcon style={{ fontSize: 28 }} />
        ) : (
          <BookmarkBorderIcon style={{ fontSize: 28 }} />
        )}
      </div>
      <div style={{ margin: "4px 8px 8px 8px" }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            fontWeight: 600,
            fontSize: 16,
            gap: 5,
          }}
        >
          <div
            style={{
              whiteSpace: "nowrap",
              textOverflow: "ellipsis",
              overflow: "hidden",
            }}
          >
            {movie.name}
          </div>
        </div>

        <div style={{ marginTop: 5 }}>
          <Rating value={movie.rating || 0} readonly />
        </div>

        <div style={{ marginTop: 5 }}>
          <LabelGroup labels={movie.labels} />
        </div>
      </div>
    </Card>
  );
}

// app/src/components/MovieCard.vue
<template>
  <v-card v-if="value" outlined>
    <v-hover v-slot:default="{ hover }">
      <a :href="`#/movie/${value._id}`">
        <v-img
          contain
          :aspect-ratio="ratio"
          class="hover"
          v-ripple
          eager
          :src="hover ? backCover : frontCover"
        >
          <div
            style="z-index: 6"
            class="white--text body-2 font-weight-bold duration-stamp"
            v-if="value.duration"
          >{{ movieDuration }}</div>

          <div class="corner-actions">
            <v-btn
              light
              class="elevation-2 mr-1"
              @click.stop.prevent="favorite"
              icon
              style="background: #fafafa;"
            >
              <v-icon
                :color="value.favorite ? 'red' : undefined"
              >{{ value.favorite ? 'mdi-heart' : 'mdi-heart-outline' }}</v-icon>
            </v-btn>
            <v-btn
              light
              class="elevation-2"
              @click.stop.prevent="bookmark"
              icon
              style="background: #fafafa;"
            >
              <v-icon>{{ value.bookmark ? 'mdi-bookmark-check' : 'mdi-bookmark-outline' }}</v-icon>
            </v-btn>
          </div>
        </v-img>
      </a>
    </v-hover>

    <v-card-title>
      <span
        :title="value.name"
        style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis"
      >{{ value.name }}</span>
    </v-card-title>
    <v-card-subtitle v-if="value.actors.length" class="pt-0 pb-0">
      Featuring
      <span v-html="actorLinks"></span>
    </v-card-subtitle>
    <v-card-subtitle class="pt-0 pb-0">{{ value.scenes.length }} scenes</v-card-subtitle>
    <v-rating
      half-increments
      class="ml-3 mb-2"
      :value="value.rating / 2"
      background-color="grey"
      color="amber"
      dense
      readonly
    ></v-rating>
    <div class="pa-2">
      <v-chip
        label
        class="mr-1 mb-1"
        small
        outlined
        v-for="label in labelNames"
        :key="label"
      >{{ label }}</v-chip>
    </div>
  </v-card>
</template>

<script lang="ts">
import { Component, Vue, Prop } from "vue-property-decorator";
import ApolloClient, { serverBase } from "../apollo";
import gql from "graphql-tag";
import IMovie from "../types/movie";
import { copy } from "../util/object";
import moment from "moment";

@Component
export default class MovieCard extends Vue {
  @Prop(Object) value!: IMovie;
  @Prop({ default: 0.71 }) ratio!: number;

  get movieDuration() {
    if (this.value && this.value.duration)
      return moment()
        .startOf("day")
        .seconds(this.value.duration)
        .format(this.value.duration < 3600 ? "mm:ss" : "H:mm:ss");
    return "";
  }

  favorite() {
    ApolloClient.mutate({
      mutation: gql`
        mutation($ids: [String!]!, $opts: MovieUpdateOpts!) {
          updateMovies(ids: $ids, opts: $opts) {
            favorite
          }
        }
      `,
      variables: {
        ids: [this.value._id],
        opts: {
          favorite: !this.value.favorite
        }
      }
    }).then(res => {
      const movie = copy(this.value);
      movie.favorite = res.data.updateMovies[0].favorite;
      this.$emit("input", movie);
    });
  }

  bookmark() {
    ApolloClient.mutate({
      mutation: gql`
        mutation($ids: [String!]!, $opts: MovieUpdateOpts!) {
          updateMovies(ids: $ids, opts: $opts) {
            bookmark
          }
        }
      `,
      variables: {
        ids: [this.value._id],
        opts: {
          bookmark: !this.value.bookmark
        }
      }
    }).then(res => {
      const movie = copy(this.value);
      movie.bookmark = res.data.updateMovies[0].bookmark;
      this.$emit("input", movie);
    });
  }

  get labelNames() {
    return this.value.labels.map(l => l.name).sort();
  }

  get actorLinks() {
    const names = this.value.actors.map(
      a => `<a class="accent--text" href="#/actor/${a._id}">${a.name}</a>`
    );
    names.sort();
    return names.join(", ");
  }

  get frontCover() {
    if (this.value.frontCover)
      return `${serverBase}/image/${
        this.value.frontCover._id
      }?password=${localStorage.getItem("password")}`;
    return ``;
  }

  get backCover() {
    if (this.value.backCover)
      return `${serverBase}/image/${
        this.value.backCover._id
      }?password=${localStorage.getItem("password")}`;
    return this.frontCover;
  }
}
</script>

<style lang="scss" scoped>
.duration-stamp {
  padding: 4px;
  border-radius: 4px;
  background: #000000a0;
  position: absolute;
  bottom: 5px;
  right: 5px;
}

.corner-actions {
  position: absolute;
  bottom: 5px;
  left: 5px;
}
</style>
