// components/Topbar.tsx
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import Axios from "axios";

export default function Topbar() {
  const router = useRouter();
  const [version, setVersion] = useState("");
  const [searchText, setSearchText] = useState("");

  useEffect(() => {
    Axios.get("/api/version").then((res) => {
      setVersion(res.data.result);
    });
  }, []);

  return (
    <div className="topbar">
      <div style={{ width: "100%", display: "flex", alignItems: "center", padding: 12, gap: 4 }}>
        <img
          onClick={() => router.push("/")}
          className="hover"
          width={36}
          height={36}
          src="/assets/favicon.png"
        />
        <div style={{ fontSize: 14, fontWeight: "bold", opacity: 0.75 }}>{version}</div>
        <div style={{ flexGrow: 1 }}></div>
        <input
          type="text"
          placeholder="Search"
          value={searchText}
          onChange={(ev) => setSearchText(ev.target.value)}
          onKeyDown={(ev) => {
            if (ev.key === "Enter") {
              router.push(`/search?q=${searchText}`);
            }
          }}
        />
      </div>
    </div>
  );
}

// components/topbar/index.vue
<template>
  <div class="topbar-wrapper flex">
    <div class="hover">
      <nuxt-link style="display: inherit" to="/">
        <img width="32" height="32" src="/assets/favicon.png" alt="" />
      </nuxt-link>
    </div>
    <div style="flex-grow: 1"></div>
    <pv-input
      @keydown.enter="search"
      v-model="searchQuery"
      type="text"
      placeholder="Find content"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, useRouter } from "@nuxtjs/composition-api";
import PvInput from "../input.vue";

export default defineComponent({
  components: { PvInput },
  setup() {
    const router = useRouter();

    const searchQuery = ref("");

    function search() {
      router.push({
        path: "/search",
        query: {
          q: searchQuery.value,
        },
      });
    }

    return {
      searchQuery,
      search,
    };
  },
});
</script>

<style scoped>
.topbar-wrapper {
  width: 100%;
  border-bottom: 1px solid #f0f0f0;
  padding: 8px;
}
</style>
