// pages/search.vue
<template>
  <div>
    <!-- Actors -->
    <div>
      <div class="category-header" style="margin-bottom: 5px">
        <pre><b>{{ actorResult.numItems }}</b> actors found</pre>
      </div>
      <div>
        <list-container min="150px" max="1fr">
          <div
            style="display: flex; flex-direction: column"
            v-for="actor in actorResult.items"
            :key="actor._id"
          >
            <div
              style="
                display: flex;
                align-items: center;
                flex-grow: 1;
                overflow: hidden;
                box-shadow: rgba(0, 0, 0, 0.15) 1.95px 1.95px 2.6px !important;
              "
              class="card rounded hover"
            >
              <nuxt-link :to="`/actor/${actor._id}`">
                <img
                  style="display: block; width: 100%; height: auto"
                  :src="`/api/media/image/${actor.thumbnail && actor.thumbnail._id}/thumbnail`"
                />
              </nuxt-link>
            </div>
            <div style="font-size: 16px; margin-top: 10px; text-align: center">
              <b>{{ actor.name }}</b>
            </div>
          </div>
        </list-container>
      </div>
    </div>
    <!-- Actors end -->

    <!-- Scenes -->
    <div>
      <div class="category-header" style="margin-bottom: 5px">
        <pre><b>{{ sceneResult.numItems }}</b> scenes found</pre>
      </div>
      <div>
        <list-container>
          <div v-for="scene in sceneResult.items" :key="scene._id">
            <scene-card style="height: 100%" :scene="scene"></scene-card>
          </div>
        </list-container>
      </div>
    </div>
    <!-- Scenes end -->

    <!-- Movies -->
    <div>
      <div class="category-header" style="margin-bottom: 5px">
        <pre><b>{{ movieResult.numItems }}</b> movies found</pre>
      </div>
      <div>
        <list-container>
          <div v-for="movie in movieResult.items" :key="movie._id">
            <div>
              <movie-card style="height: 100%" :movie="movie"></movie-card>
            </div>
          </div>
        </list-container>
      </div>
    </div>
    <!-- Movies end -->
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  useRoute,
  ref,
  useFetch,
  useContext,
  useMeta,
  onMounted,
  ssrRef,
} from "@nuxtjs/composition-api";
import axios from "axios";

import ListContainer from "../components/list_container.vue";
import MovieCard from "../components/movie_card.vue";
import SceneCard from "../components/scene_card.vue";
import { getUrl } from "../client/util/url";
import { sceneCardFragment } from "../client/fragments/scene";

async function searchAll(query: string) {
  const { data } = await axios.post(
    getUrl("/api/ql", process.server),
    {
      query: `
        query($sc: SceneSearchQuery!, $ac: ActorSearchQuery!, $mo: MovieSearchQuery!) {
          getScenes(query: $sc) {
            items {
              ...SceneCard
            }
            numItems
          }
          getActors(query: $ac) {
            items {
              _id
              name
              thumbnail {
                _id
                color
              }
            }
            numItems
          }
          getMovies(query: $mo) {
            items {
              _id
              name
              duration
              favorite
              bookmark
              rating
              frontCover {
                _id
                color
              }
              actors {
                _id
                name
              }
              labels {
                _id
                name
                color
              }
              studio {
                _id
                name
              }
            }
            numItems
          }
        }

        ${sceneCardFragment}
      `,
      variables: {
        sc: {
          query,
          take: 8,
        },
        ac: {
          query,
          take: 8,
        },
        mo: {
          query,
          take: 8,
        },
      },
    },
    {
      headers: {
        "x-pass": "xxx",
      },
    }
  );

  return {
    sceneResult: data.data.getScenes,
    actorResult: data.data.getActors,
    movieResult: data.data.getMovies,
  };
}

export default defineComponent({
  components: {
    ListContainer,
    SceneCard,
    MovieCard,
  },
  watch: {
    "$route.query": "$fetch",
  },
  head: {},
  setup() {
    const { error } = useContext();
    const route = useRoute();

    const titleRef = ssrRef("", "title-ref");
    const { title } = useMeta();

    const sceneResult = ref([]);
    const actorResult = ref([]);
    const movieResult = ref([]);

    useFetch(async () => {
      try {
        const query = String(route.value.query.q);
        const result = await searchAll(query);

        sceneResult.value = result.sceneResult;
        actorResult.value = result.actorResult;
        movieResult.value = result.movieResult;

        titleRef.value = `Results for "${query}"`;
        title.value = titleRef.value;
      } catch (fetchError) {
        console.error(fetchError);
        if (!fetchError.response) {
          return error({
            statusCode: 500,
            message: "Internal error - check console",
          });
        } else {
          return error({
            statusCode: fetchError.response.status,
            message: fetchError.response.data,
          });
        }
      }
    });

    onMounted(() => {
      title.value = titleRef.value;
    });

    return { sceneResult, actorResult, movieResult };
  },
});
</script>

<style scoped>
pre {
  margin-bottom: 0;
}

.category-header {
  font-size: 18px;
}
</style>

// pages/search.tsx
import axios from "axios";
import { GetServerSideProps } from "next";
import ActorCard from "../components/ActorGridItem";
import { movieCardFragment } from "../fragments/movie";
import { sceneCardFragment } from "../fragments/scene";
import Typography from "@mui/material/Typography";
import { useTranslations } from "next-intl";
import { IPaginationResult } from "../types/pagination";
import { IActor } from "../types/actor";
import { IMovie } from "../types/movie";
import { IScene } from "../types/scene";

function thumbnailUrl(thumbnail: string) {
  return `/api/media/image/${thumbnail}/thumbnail?password=xxx`;
}

async function searchAll(query: string) {
  const { data } = await axios.post(
    "http://localhost:3000/api/ql",
    {
      query: `
        query($sc: SceneSearchQuery!, $ac: ActorSearchQuery!, $mo: MovieSearchQuery!) {
          getScenes(query: $sc) {
            items {
              ...SceneCard
            }
            numItems
          }
          getActors(query: $ac) {
            items {
              _id
              name
              thumbnail {
                _id
                color
              }
            }
            numItems
          }
          getMovies(query: $mo) {
            items {
              ...MovieCard
            }
            numItems
          }
        }

        ${sceneCardFragment}
        ${movieCardFragment}
      `,
      variables: {
        sc: {
          query,
          take: 10,
        },
        ac: {
          query,
          take: 10,
        },
        mo: {
          query,
          take: 10,
        },
      },
    },
    {
      headers: {
        "x-pass": "xxx",
      },
    }
  );

  return {
    sceneResult: data.data.getScenes,
    actorResult: data.data.getActors,
    movieResult: data.data.getMovies,
  };
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const result = await searchAll(String(query.q));
  return {
    props: {
      ...result,
    },
  };
};

export default function SearchPage(props: {
  actorResult: IPaginationResult<IActor>;
  movieResult: IPaginationResult<IMovie>;
  sceneResult: IPaginationResult<IScene>;
}) {
  const t = useTranslations();

  const { actorResult, movieResult, sceneResult } = props;

  return (
    <div>
      {/* Actors */}
      <div style={{ marginBottom: 20 }}>
        <Typography sx={{ marginBottom: "10px" }} variant="h6">
          {t("foundActors", { numItems: actorResult.numItems })}
        </Typography>
        <div
          className="list-container"
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
            gridGap: 4,
          }}
        >
          {actorResult.items.map((actor) => (
            <ActorCard
              key={actor._id}
              favorite={actor.favorite}
              name={actor.name}
              thumbnail={actor.thumbnail?._id}
            ></ActorCard>
          ))}
        </div>
      </div>
      {/* Movies */}
      <div style={{ marginBottom: 20 }}>
        <Typography sx={{ marginBottom: "10px" }} variant="h6">
          {t("foundMovies", { numItems: movieResult.numItems })}
        </Typography>
        <div
          className="list-container"
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
            gridGap: 4,
          }}
        >
          {movieResult.items.map((movie) => (
            <div key={movie._id}>
              <img
                style={{ borderRadius: 8, objectFit: "cover" }}
                width="100%"
                height="100%"
                src={thumbnailUrl(movie.frontCover?._id || "null")}
              />
            </div>
          ))}
        </div>
      </div>
      {/* Scenes */}
      <div>
        <Typography sx={{ marginBottom: "10px" }} variant="h6">
          {t("foundScenes", { numItems: sceneResult.numItems })}
        </Typography>
        <div
          className="list-container"
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
            gridGap: 4,
          }}
        >
          {sceneResult.items.map((scene) => (
            <div key={scene._id}>
              <img
                style={{ borderRadius: 8, objectFit: "cover" }}
                width="100%"
                height="100%"
                src={thumbnailUrl(scene.thumbnail?._id || "null")}
              />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
